### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by dvzrv** [x42/sound-gambit#2]
Hi! When attempting to package this software for Arch Linux I noticed, that the project is missing a license file.

Judging from the source code this is all GPL-3.0-or-later, so (for me) technically a LICENSE or COPYING file is not required, but it might be for more strict downstream distributions. Additionally, adding such a file probably makes it more obvious to potential contributors or users under what terms modifications are accepted and under what terms the code may be distributed.

**Comment by x42** [comment]
Thanks for the heads up, added just now as v0.6-2 b503f9d
